<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Moongate.Network\Moongate.Network.csproj"/>
        <ProjectReference Include="..\Moongate.Abstractions\Moongate.Abstractions.csproj"/>
        <ProjectReference Include="..\Moongate.UO.Data\Moongate.UO.Data.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Data\"/>
        <Folder Include="Packets\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.301">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
