<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Moongate.Core\Moongate.Core.csproj"/>
        <ProjectReference Include="..\Moongate.Abstractions\Moongate.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.301">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
