<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Moongate.Core\Moongate.Core.csproj"/>
        <ProjectReference Include="..\Moongate.Abstractions\Moongate.Abstractions.csproj"/>
        <ProjectReference Include="..\Moongate.Persistence\Moongate.Persistence.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Moongate.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.301">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
